var myModule=angular.module("myApp",["ui.router"]);
myModule.config(function($stateProvider,$urlRouterProvider){
	$urlRouterProvider.when("","/0");
	$stateProvider
//list
	.state("0",{
		url:"/0",
		templateUrl:"view/list.html",
		controller:"0"
	})
	.state("0.0",{
		url:"/0",
		templateUrl:"view/list_info.html",
		controller:"0.0"
	})
	.state("0.1",{
		url:"/1",
		templateUrl:"view/list_info.html",
		controller:"0.1"
	})
	.state("0.2",{
		url:"/2",
		templateUrl:"view/list_info.html",
		controller:"0.2"
	})
	.state("0.3",{
		url:"/3",
		templateUrl:"view/list_info.html",
		controller:"0.3"
	})
	.state("0.4",{
		url:"/4",
		templateUrl:"view/list_info.html",
		controller:"0.4"
	})
	.state("0.5",{
		url:"/5",
		templateUrl:"view/list_info.html",
		controller:"0.5"
	})
	.state("0.6",{
		url:"/6",
		templateUrl:"view/list_info.html",
		controller:"0.6"
	})
	.state("0.7",{
		url:"/7",
		templateUrl:"view/list_info.html",
		controller:"0.7"
	})
	.state("0.8",{
		url:"/8",
		templateUrl:"view/list_info.html",
		controller:"0.8"
	})
//发现
	.state("1",{
		url:"/1",
		templateUrl:"view/faxian.html",
		controller:"1"
	})
	.state("1.0",{
		url:"/0",
		templateUrl:"view/list_info.html",
		controller:"1.0"
	})
	.state("1.1",{
		url:"/1",
		templateUrl:"view/list_info.html",
		controller:"1.1"
	})
	.state("1.2",{
		url:"/2",
		templateUrl:"view/list_info.html",
		controller:"1.2"
	})
	.state("1.3",{
		url:"/3",
		templateUrl:"view/list_info.html",
		controller:"1.3"
	})
	.state("1.4",{
		url:"/4",
		templateUrl:"view/list_info.html",
		controller:"1.4"
	})
//首页
	.state("2",{
		url:"/2",
		template:"2222"
	})
//全部
	.state("3",{
		url:"/3",
		templateUrl:"view/all.html",
		controller:"3"
	})
//其他
	.state("4",{
		url:"/4",
		templateUrl:"view/all.html",
		controller:"4"
	})
	.state("5",{
		url:"/5",
		templateUrl:"view/all.html",
		controller:"5"
	})
	.state("6",{
		url:"/6",
		templateUrl:"view/all.html",
		controller:"6"
	})
	.state("7",{
		url:"/7",
		templateUrl:"view/all.html",
		controller:"7"
	})
	.state("8",{
		url:"/8",
		templateUrl:"view/all.html",
		controller:"8"
	})
	.state("9",{
		url:"/9",
		templateUrl:"view/all.html",
		controller:"9"
	})
})
//controller
	myModule.controller("ctrl",function($rootScope,$http){
		$http({
			url:"data.txt"
		}).success(function(res){
			console.log(res)
			$rootScope.data=res;
		})
	})
//列表-controller
	myModule.controller("0",function($scope,$rootScope,$state){
		$state.go("0.0")
		$scope.data=$rootScope.data["列表"];
		// console.log($scope.data)
	})
	myModule.controller("0.0",function($scope,$rootScope){
		$scope.data=$rootScope.data["列表"][0].content;
	})
	myModule.controller("0.1",function($scope,$rootScope){
		$scope.data=$rootScope.data["列表"][1].content;
	})
	myModule.controller("0.2",function($scope,$rootScope){
		$scope.data=$rootScope.data["列表"][2].content;
	})
	myModule.controller("0.3",function($scope,$rootScope){
		$scope.data=$rootScope.data["列表"][3].content;
	})
	myModule.controller("0.4",function($scope,$rootScope){
		$scope.data=$rootScope.data["列表"][4].content;
	})
	myModule.controller("0.5",function($scope,$rootScope){
		$scope.data=$rootScope.data["列表"][5].content;
	})
	myModule.controller("0.6",function($scope,$rootScope){
		$scope.data=$rootScope.data["列表"][6].content;
	})
	myModule.controller("0.7",function($scope,$rootScope){
		$scope.data=$rootScope.data["列表"][7].content;
	})
	myModule.controller("0.8",function($scope,$rootScope){
		$scope.data=$rootScope.data["列表"][8].content;
	})
//发现-controller
	myModule.controller("1",function($scope,$rootScope,$state){
		$state.go("1.0")
		$scope.data=$rootScope.data["发现"];
		// console.log($scope.data)
	})
	myModule.controller("1.0",function($scope,$rootScope){
		$scope.data=$rootScope.data["发现"]["功能"];
	})
	myModule.controller("1.1",function($scope,$rootScope){
		$scope.data=$rootScope.data["发现"]["口感"];
	})

	myModule.controller("1.2",function($scope,$rootScope){
		$scope.data=$rootScope.data["发现"]["节日"];
	})

	myModule.controller("1.3",function($scope,$rootScope){
		$scope.data=$rootScope.data["发现"]["场合"];
	})
	myModule.controller("1.4",function($scope,$rootScope){
		$scope.data=$rootScope.data["发现"]["人群"];
	})
//全部-controller
	myModule.controller("3",function($scope,$rootScope){
		$scope.data=$rootScope.data["全部"].content;
	})
	myModule.controller("4",function($scope,$rootScope){
		$scope.data=$rootScope.data["进口"].content;
	})
	myModule.controller("5",function($scope,$rootScope){
		$scope.data=$rootScope.data["特产"].content;
	})
	myModule.controller("6",function($scope,$rootScope){
		$scope.data=$rootScope.data["零食"].content;
	})
	myModule.controller("7",function($scope,$rootScope){
		$scope.data=$rootScope.data["五谷"].content;
	})
	myModule.controller("8",function($scope,$rootScope){
		$scope.data=$rootScope.data["茶饮"].content;
	})
	myModule.controller("9",function($scope,$rootScope){
		$scope.data=$rootScope.data["滋补"].content;
	})

